/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AlertCertainty = 'Observed' | 'Likely' | 'Possible' | 'Unlikely' | 'Unknown';

export const AlertCertainty = {
    Observed: 'Observed' as AlertCertainty,
    Likely: 'Likely' as AlertCertainty,
    Possible: 'Possible' as AlertCertainty,
    Unlikely: 'Unlikely' as AlertCertainty,
    Unknown: 'Unknown' as AlertCertainty
};