/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AlertSeverity = 'Extreme' | 'Severe' | 'Moderate' | 'Minor' | 'Unknown';

export const AlertSeverity = {
    Extreme: 'Extreme' as AlertSeverity,
    Severe: 'Severe' as AlertSeverity,
    Moderate: 'Moderate' as AlertSeverity,
    Minor: 'Minor' as AlertSeverity,
    Unknown: 'Unknown' as AlertSeverity
};