/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlertAtomEntryAuthor } from './alertAtomEntryAuthor';
import { AlertXMLParameter } from './alertXMLParameter';

/**
 * An alert entry in an Atom feed
 */
export interface AlertAtomEntry { 
    id?: string;
    updated?: string;
    published?: string;
    author?: AlertAtomEntryAuthor;
    summary?: string;
    event?: string;
    sent?: string;
    effective?: string;
    expires?: string;
    status?: string;
    msgType?: string;
    category?: string;
    urgency?: string;
    severity?: string;
    certainty?: string;
    areaDesc?: string;
    polygon?: string;
    geocode?: Array<AlertXMLParameter>;
    parameter?: Array<AlertXMLParameter>;
}