/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AlertStatus = 'Actual' | 'Exercise' | 'System' | 'Test' | 'Draft';

export const AlertStatus = {
    Actual: 'Actual' as AlertStatus,
    Exercise: 'Exercise' as AlertStatus,
    System: 'System' as AlertStatus,
    Test: 'Test' as AlertStatus,
    Draft: 'Draft' as AlertStatus
};