/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlertId } from './alertId';

export interface AlertReferences { 
    /**
     * An API link to the prior alert.
     */
    id?: string;
    identifier?: AlertId;
    /**
     * The sender of the prior alert.
     */
    sender?: string;
    /**
     * The time the prior alert was sent.
     */
    sent?: Date;
}