/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Alert } from './alert';
import { GeoJsonFeature } from './geoJsonFeature';
import { GeoJsonGeometry } from './geoJsonGeometry';
import { JsonLdContext } from './jsonLdContext';

export interface AlertGeoJson extends GeoJsonFeature { 
    properties?: Alert;
}
export namespace AlertGeoJson {
}