/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlertCollection } from './alertCollection';
import { AlertCollectionGeoJsonFeatures } from './alertCollectionGeoJsonFeatures';
import { GeoJsonFeatureCollection } from './geoJsonFeatureCollection';
import { PaginationInfo } from './paginationInfo';

export interface AlertCollectionGeoJson extends GeoJsonFeatureCollection { 
    /**
     * A title describing the alert collection
     */
    title?: string;
    /**
     * The last time a change occurred to this collection
     */
    updated?: Date;
    pagination?: PaginationInfo;
    // features?: Array<AlertCollectionGeoJsonFeatures>;
}
export namespace AlertCollectionGeoJson {
}