/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AlertUrgency = 'Immediate' | 'Expected' | 'Future' | 'Past' | 'Unknown';

export const AlertUrgency = {
    Immediate: 'Immediate' as AlertUrgency,
    Expected: 'Expected' as AlertUrgency,
    Future: 'Future' as AlertUrgency,
    Past: 'Past' as AlertUrgency,
    Unknown: 'Unknown' as AlertUrgency
};