/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NWSZoneID } from './nWSZoneID';

/**
 * Lists of codes for NWS public zones and counties affected by the alert.
 */
export interface AlertGeocode { 
    /**
     * A list of NWS public zone or county identifiers.
     */
    UGC?: Array<NWSZoneID>;
    /**
     * A list of SAME (Specific Area Message Encoding) codes for affected counties.
     */
    SAME?: Array<string>;
}