/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AlertMessageType = 'Alert' | 'Update' | 'Cancel' | 'Ack' | 'Error';

export const AlertMessageType = {
    Alert: 'Alert' as AlertMessageType,
    Update: 'Update' as AlertMessageType,
    Cancel: 'Cancel' as AlertMessageType,
    Ack: 'Ack' as AlertMessageType,
    Error: 'Error' as AlertMessageType
};