/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MarineAreaCode } from './marineAreaCode';
import { StateTerritoryCode } from './stateTerritoryCode';

/**
 * State/territory codes and marine area codes
 */
export type AreaCode = StateTerritoryCode | MarineAreaCode;