/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJsonFeature } from './geoJsonFeature';
import { JsonLdContext } from './jsonLdContext';

/**
 * A GeoJSON feature collection. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export interface GeoJsonFeatureCollection { 
    context?: JsonLdContext;
    type: GeoJsonFeatureCollection.TypeEnum;
    features: Array<GeoJsonFeature>;
}
export namespace GeoJsonFeatureCollection {
    export type TypeEnum = 'FeatureCollection';
    export const TypeEnum = {
        FeatureCollection: 'FeatureCollection' as TypeEnum
    };
}