/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GridpointHazardsValue } from './gridpointHazardsValue';
import { ISO8601Interval } from './iSO8601Interval';

export interface GridpointHazardsValues { 
    validTime: ISO8601Interval;
    value: Array<GridpointHazardsValue>;
}