/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Denotes the units used in the textual portions of the forecast.
 */
export type GridpointForecastUnits = 'us' | 'si';

export const GridpointForecastUnits = {
    Us: 'us' as GridpointForecastUnits,
    Si: 'si' as GridpointForecastUnits
};