/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A value object representing an expected hazard.
 */
export interface GridpointHazardsValue { 
    /**
     * Hazard code. This value will correspond to a P-VTEC phenomenon code as defined in NWS Directive 10-1703. 
     */
    phenomenon: string;
    /**
     * Significance code. This value will correspond to a P-VTEC significance code as defined in NWS Directive 10-1703. This will most frequently be \"A\" for a watch or \"Y\" for an advisory. 
     */
    significance: string;
    /**
     * Event number. If this hazard refers to a national or regional center product (such as a Storm Prediction Center convective watch), this value will be the sequence number of that product. 
     */
    eventNumber: number;
}