/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeometryString } from './geometryString';
import { GridpointForecastPeriod } from './gridpointForecastPeriod';
import { GridpointForecastUnits } from './gridpointForecastUnits';
import { ISO8601Interval } from './iSO8601Interval';
import { JsonLdContext } from './jsonLdContext';
import { QuantitativeValue } from './quantitativeValue';

/**
 * A multi-day forecast for a 2.5km grid square.
 */
export interface GridpointForecast { 
    context?: JsonLdContext;
    geometry?: GeometryString;
    units?: GridpointForecastUnits;
    /**
     * The internal generator class used to create the forecast text (used for NWS debugging).
     */
    forecastGenerator?: string;
    /**
     * The time this forecast data was generated.
     */
    generatedAt?: Date;
    /**
     * The last update time of the data this forecast was generated from.
     */
    updateTime?: Date;
    /**
     * This property is deprecated (use updateTime instead).
     */
    updated?: Date;
    validTimes?: ISO8601Interval;
    elevation?: QuantitativeValue;
    /**
     * An array of forecast periods.
     */
    periods?: Array<GridpointForecastPeriod>;
}