/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2003Icons } from './inlineResponse2003Icons';
import { JsonLdContext } from './jsonLdContext';

export interface InlineResponse2003 { 
    context?: JsonLdContext;
    icons: { [key: string]: InlineResponse2003Icons; };
}