/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2002Glossary { 
    /**
     * The term being defined
     */
    term?: string;
    /**
     * A definition for the term
     */
    definition?: string;
}