/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2002Glossary } from './inlineResponse2002Glossary';
import { JsonLdContext } from './jsonLdContext';

export interface InlineResponse2002 { 
    context?: JsonLdContext;
    /**
     * A list of glossary terms
     */
    glossary?: Array<InlineResponse2002Glossary>;
}