/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse200 { 
    /**
     * The total number of active alerts
     */
    total?: number;
    /**
     * The total number of active alerts affecting land zones
     */
    land?: number;
    /**
     * The total number of active alerts affecting marine zones
     */
    marine?: number;
    /**
     * Active alerts by marine region
     */
    regions?: { [key: string]: number; };
    /**
     * Active alerts by area (state/territory)
     */
    areas?: { [key: string]: number; };
    /**
     * Active alerts by NWS public zone or county code
     */
    zones?: { [key: string]: number; };
}