/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Land region code. These correspond to the six NWS regional headquarters: * AR: Alaska Region * CR: Central Region * ER: Eastern Region * PR: Pacific Region * SR: Southern Region * WR: Western Region 
 */
export type LandRegionCode = 'AR' | 'CR' | 'ER' | 'PR' | 'SR' | 'WR';

export const LandRegionCode = {
    AR: 'AR' as LandRegionCode,
    CR: 'CR' as LandRegionCode,
    ER: 'ER' as LandRegionCode,
    PR: 'PR' as LandRegionCode,
    SR: 'SR' as LandRegionCode,
    WR: 'WR' as LandRegionCode
};