/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Marine area code as defined in NWS Directive 10-302: * AM: Western North Atlantic Ocean and along U.S. East Coast south of Currituck Beach Light NC following the coastline into Gulf of Mexico to Ocean Reef FL including the Caribbean * AN: Western North Atlantic Ocean and along U.S. East Coast from Canadian border south to Currituck Beach Light NC * GM: Gulf of Mexico and along the U.S. Gulf Coast from the Mexican border to Ocean Reef FL * LC: Lake St. Clair * LE: Lake Erie * LH: Lake Huron * LM: Lake Michigan * LO: Lake Ontario * LS: Lake Superior * PH: Central Pacific Ocean including Hawaiian waters * PK: North Pacific Ocean near Alaska and along Alaska coastline including the Bering Sea and the Gulf of Alaska * PM: Western Pacific Ocean including Mariana Island waters * PS: South Central Pacific Ocean including American Samoa waters * PZ: Eastern North Pacific Ocean and along U.S. West Coast from Canadian border to Mexican border * SL: St. Lawrence River above St. Regis 
 */
export type MarineAreaCode = 'AM' | 'AN' | 'GM' | 'LC' | 'LE' | 'LH' | 'LM' | 'LO' | 'LS' | 'PH' | 'PK' | 'PM' | 'PS' | 'PZ' | 'SL';

export const MarineAreaCode = {
    AM: 'AM' as MarineAreaCode,
    AN: 'AN' as MarineAreaCode,
    GM: 'GM' as MarineAreaCode,
    LC: 'LC' as MarineAreaCode,
    LE: 'LE' as MarineAreaCode,
    LH: 'LH' as MarineAreaCode,
    LM: 'LM' as MarineAreaCode,
    LO: 'LO' as MarineAreaCode,
    LS: 'LS' as MarineAreaCode,
    PH: 'PH' as MarineAreaCode,
    PK: 'PK' as MarineAreaCode,
    PM: 'PM' as MarineAreaCode,
    PS: 'PS' as MarineAreaCode,
    PZ: 'PZ' as MarineAreaCode,
    SL: 'SL' as MarineAreaCode
};