/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Marine region code. These are groups of marine areas combined. * AL: Alaska waters (PK) * AT: Atlantic Ocean (AM, AN) * GL: Great Lakes (LC, LE, LH, LM, LO, LS, SL) * GM: Gulf of Mexico (GM) * PA: Eastern Pacific Ocean and U.S. West Coast (PZ) * PI: Central and Western Pacific (PH, PM, PS) 
 */
export type MarineRegionCode = 'AL' | 'AT' | 'GL' | 'GM' | 'PA' | 'PI';

export const MarineRegionCode = {
    AL: 'AL' as MarineRegionCode,
    AT: 'AT' as MarineRegionCode,
    GL: 'GL' as MarineRegionCode,
    GM: 'GM' as MarineRegionCode,
    PA: 'PA' as MarineRegionCode,
    PI: 'PI' as MarineRegionCode
};