/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * An object representing a decoded METAR phenomenon string.
 */
export interface MetarPhenomenon { 
    intensity: MetarPhenomenon.IntensityEnum;
    modifier: MetarPhenomenon.ModifierEnum;
    weather: MetarPhenomenon.WeatherEnum;
    rawString: string;
    inVicinity?: boolean;
}
export namespace MetarPhenomenon {
    export type IntensityEnum = 'light' | 'heavy';
    export const IntensityEnum = {
        Light: 'light' as IntensityEnum,
        Heavy: 'heavy' as IntensityEnum
    };
    export type ModifierEnum = 'patches' | 'blowing' | 'low_drifting' | 'freezing' | 'shallow' | 'partial' | 'showers';
    export const ModifierEnum = {
        Patches: 'patches' as ModifierEnum,
        Blowing: 'blowing' as ModifierEnum,
        LowDrifting: 'low_drifting' as ModifierEnum,
        Freezing: 'freezing' as ModifierEnum,
        Shallow: 'shallow' as ModifierEnum,
        Partial: 'partial' as ModifierEnum,
        Showers: 'showers' as ModifierEnum
    };
    export type WeatherEnum = 'fog_mist' | 'dust_storm' | 'dust' | 'drizzle' | 'funnel_cloud' | 'fog' | 'smoke' | 'hail' | 'snow_pellets' | 'haze' | 'ice_crystals' | 'ice_pellets' | 'dust_whirls' | 'spray' | 'rain' | 'sand' | 'snow_grains' | 'snow' | 'squalls' | 'sand_storm' | 'thunderstorms' | 'unknown' | 'volcanic_ash';
    export const WeatherEnum = {
        FogMist: 'fog_mist' as WeatherEnum,
        DustStorm: 'dust_storm' as WeatherEnum,
        Dust: 'dust' as WeatherEnum,
        Drizzle: 'drizzle' as WeatherEnum,
        FunnelCloud: 'funnel_cloud' as WeatherEnum,
        Fog: 'fog' as WeatherEnum,
        Smoke: 'smoke' as WeatherEnum,
        Hail: 'hail' as WeatherEnum,
        SnowPellets: 'snow_pellets' as WeatherEnum,
        Haze: 'haze' as WeatherEnum,
        IceCrystals: 'ice_crystals' as WeatherEnum,
        IcePellets: 'ice_pellets' as WeatherEnum,
        DustWhirls: 'dust_whirls' as WeatherEnum,
        Spray: 'spray' as WeatherEnum,
        Rain: 'rain' as WeatherEnum,
        Sand: 'sand' as WeatherEnum,
        SnowGrains: 'snow_grains' as WeatherEnum,
        Snow: 'snow' as WeatherEnum,
        Squalls: 'squalls' as WeatherEnum,
        SandStorm: 'sand_storm' as WeatherEnum,
        Thunderstorms: 'thunderstorms' as WeatherEnum,
        Unknown: 'unknown' as WeatherEnum,
        VolcanicAsh: 'volcanic_ash' as WeatherEnum
    };
}