/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Three-letter identifier for a Center Weather Service Unit (CWSU).
 */
export type NWSCenterWeatherServiceUnitId = 'ZAB' | 'ZAN' | 'ZAU' | 'ZBW' | 'ZDC' | 'ZDV' | 'ZFA' | 'ZFW' | 'ZHU' | 'ZID' | 'ZJX' | 'ZKC' | 'ZLA' | 'ZLC' | 'ZMA' | 'ZME' | 'ZMP' | 'ZNY' | 'ZOA' | 'ZOB' | 'ZSE' | 'ZTL';

export const NWSCenterWeatherServiceUnitId = {
    ZAB: 'ZAB' as NWSCenterWeatherServiceUnitId,
    ZAN: 'ZAN' as NWSCenterWeatherServiceUnitId,
    ZAU: 'ZAU' as NWSCenterWeatherServiceUnitId,
    ZBW: 'ZBW' as NWSCenterWeatherServiceUnitId,
    ZDC: 'ZDC' as NWSCenterWeatherServiceUnitId,
    ZDV: 'ZDV' as NWSCenterWeatherServiceUnitId,
    ZFA: 'ZFA' as NWSCenterWeatherServiceUnitId,
    ZFW: 'ZFW' as NWSCenterWeatherServiceUnitId,
    ZHU: 'ZHU' as NWSCenterWeatherServiceUnitId,
    ZID: 'ZID' as NWSCenterWeatherServiceUnitId,
    ZJX: 'ZJX' as NWSCenterWeatherServiceUnitId,
    ZKC: 'ZKC' as NWSCenterWeatherServiceUnitId,
    ZLA: 'ZLA' as NWSCenterWeatherServiceUnitId,
    ZLC: 'ZLC' as NWSCenterWeatherServiceUnitId,
    ZMA: 'ZMA' as NWSCenterWeatherServiceUnitId,
    ZME: 'ZME' as NWSCenterWeatherServiceUnitId,
    ZMP: 'ZMP' as NWSCenterWeatherServiceUnitId,
    ZNY: 'ZNY' as NWSCenterWeatherServiceUnitId,
    ZOA: 'ZOA' as NWSCenterWeatherServiceUnitId,
    ZOB: 'ZOB' as NWSCenterWeatherServiceUnitId,
    ZSE: 'ZSE' as NWSCenterWeatherServiceUnitId,
    ZTL: 'ZTL' as NWSCenterWeatherServiceUnitId
};