/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Three-letter identifier for a NWS Regional HQ.
 */
export type NWSRegionalHQId = 'ARH' | 'CRH' | 'ERH' | 'PRH' | 'SRH' | 'WRH';

export const NWSRegionalHQId = {
    ARH: 'ARH' as NWSRegionalHQId,
    CRH: 'CRH' as NWSRegionalHQId,
    ERH: 'ERH' as NWSRegionalHQId,
    PRH: 'PRH' as NWSRegionalHQId,
    SRH: 'SRH' as NWSRegionalHQId,
    WRH: 'WRH' as NWSRegionalHQId
};