/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type NWSZoneType = 'land' | 'marine' | 'forecast' | 'public' | 'coastal' | 'offshore' | 'fire' | 'county';

export const NWSZoneType = {
    Land: 'land' as NWSZoneType,
    Marine: 'marine' as NWSZoneType,
    Forecast: 'forecast' as NWSZoneType,
    Public: 'public' as NWSZoneType,
    Coastal: 'coastal' as NWSZoneType,
    Offshore: 'offshore' as NWSZoneType,
    Fire: 'fire' as NWSZoneType,
    County: 'county' as NWSZoneType
};