/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeometryString } from './geometryString';
import { JsonLdContext } from './jsonLdContext';
import { MetarPhenomenon } from './metarPhenomenon';
import { ObservationCloudLayers } from './observationCloudLayers';
import { QuantitativeValue } from './quantitativeValue';

export interface Observation { 
    context?: JsonLdContext;
    geometry?: GeometryString;
    id?: string;
    type?: Observation.TypeEnum;
    elevation?: QuantitativeValue;
    station?: string;
    timestamp?: Date;
    rawMessage?: string;
    textDescription?: string;
    icon?: string;
    presentWeather?: Array<MetarPhenomenon>;
    temperature?: QuantitativeValue;
    dewpoint?: QuantitativeValue;
    windDirection?: QuantitativeValue;
    windSpeed?: QuantitativeValue;
    windGust?: QuantitativeValue;
    barometricPressure?: QuantitativeValue;
    seaLevelPressure?: QuantitativeValue;
    visibility?: QuantitativeValue;
    maxTemperatureLast24Hours?: QuantitativeValue;
    minTemperatureLast24Hours?: QuantitativeValue;
    precipitationLastHour?: QuantitativeValue;
    precipitationLast3Hours?: QuantitativeValue;
    precipitationLast6Hours?: QuantitativeValue;
    relativeHumidity?: QuantitativeValue;
    windChill?: QuantitativeValue;
    heatIndex?: QuantitativeValue;
    cloudLayers?: Array<ObservationCloudLayers>;
}
export namespace Observation {
    export type TypeEnum = 'wx:ObservationStation';
    export const TypeEnum = {
        WxObservationStation: 'wx:ObservationStation' as TypeEnum
    };
}