/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJsonFeature } from './geoJsonFeature';
import { GeoJsonGeometry } from './geoJsonGeometry';
import { JsonLdContext } from './jsonLdContext';
import { Observation } from './observation';

export interface ObservationGeoJson extends GeoJsonFeature { 
    properties?: Observation;
}
export namespace ObservationGeoJson {
}