/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OfficeAddress { 
    type?: OfficeAddress.TypeEnum;
    streetAddress?: string;
    addressLocality?: string;
    addressRegion?: string;
    postalCode?: string;
}
export namespace OfficeAddress {
    export type TypeEnum = 'PostalAddress';
    export const TypeEnum = {
        PostalAddress: 'PostalAddress' as TypeEnum
    };
}