/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Links for retrieving more data from paged data sets
 */
export interface PaginationInfo { 
    /**
     * A link to the next page of records
     */
    next: string;
}