/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Detail about an error. This document conforms to RFC 7807 (Problem Details for HTTP APIs).
 */
export interface ProblemDetail { 
  [key: string]: any;


}