/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UnitOfMeasure } from './unitOfMeasure';

/**
 * A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue 
 */
export interface QuantitativeValue { 
    /**
     * A measured value
     */
    value?: number;
    /**
     * The maximum value of a range of measured values
     */
    maxValue?: number;
    /**
     * The minimum value of a range of measured values
     */
    minValue?: number;
    unitCode?: UnitOfMeasure;
    /**
     * For values in observation records, the quality control flag from the MADIS system. The definitions of these flags can be found at https://madis.ncep.noaa.gov/madis_sfc_qc_notes.shtml 
     */
    qualityControl?: QuantitativeValue.QualityControlEnum;
}
export namespace QuantitativeValue {
    export type QualityControlEnum = 'Z' | 'C' | 'S' | 'V' | 'X' | 'Q' | 'G' | 'B' | 'T';
    export const QualityControlEnum = {
        Z: 'Z' as QualityControlEnum,
        C: 'C' as QualityControlEnum,
        S: 'S' as QualityControlEnum,
        V: 'V' as QualityControlEnum,
        X: 'X' as QualityControlEnum,
        Q: 'Q' as QualityControlEnum,
        G: 'G' as QualityControlEnum,
        B: 'B' as QualityControlEnum,
        T: 'T' as QualityControlEnum
    };
}