/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type StateTerritoryCode = 'AL' | 'AK' | 'AS' | 'AR' | 'AZ' | 'CA' | 'CO' | 'CT' | 'DE' | 'DC' | 'FL' | 'GA' | 'GU' | 'HI' | 'ID' | 'IL' | 'IN' | 'IA' | 'KS' | 'KY' | 'LA' | 'ME' | 'MD' | 'MA' | 'MI' | 'MN' | 'MS' | 'MO' | 'MT' | 'NE' | 'NV' | 'NH' | 'NJ' | 'NM' | 'NY' | 'NC' | 'ND' | 'OH' | 'OK' | 'OR' | 'PA' | 'PR' | 'RI' | 'SC' | 'SD' | 'TN' | 'TX' | 'UT' | 'VT' | 'VI' | 'VA' | 'WA' | 'WV' | 'WI' | 'WY' | 'MP' | 'PW' | 'FM' | 'MH';

export const StateTerritoryCode = {
    AL: 'AL' as StateTerritoryCode,
    AK: 'AK' as StateTerritoryCode,
    AS: 'AS' as StateTerritoryCode,
    AR: 'AR' as StateTerritoryCode,
    AZ: 'AZ' as StateTerritoryCode,
    CA: 'CA' as StateTerritoryCode,
    CO: 'CO' as StateTerritoryCode,
    CT: 'CT' as StateTerritoryCode,
    DE: 'DE' as StateTerritoryCode,
    DC: 'DC' as StateTerritoryCode,
    FL: 'FL' as StateTerritoryCode,
    GA: 'GA' as StateTerritoryCode,
    GU: 'GU' as StateTerritoryCode,
    HI: 'HI' as StateTerritoryCode,
    ID: 'ID' as StateTerritoryCode,
    IL: 'IL' as StateTerritoryCode,
    IN: 'IN' as StateTerritoryCode,
    IA: 'IA' as StateTerritoryCode,
    KS: 'KS' as StateTerritoryCode,
    KY: 'KY' as StateTerritoryCode,
    LA: 'LA' as StateTerritoryCode,
    ME: 'ME' as StateTerritoryCode,
    MD: 'MD' as StateTerritoryCode,
    MA: 'MA' as StateTerritoryCode,
    MI: 'MI' as StateTerritoryCode,
    MN: 'MN' as StateTerritoryCode,
    MS: 'MS' as StateTerritoryCode,
    MO: 'MO' as StateTerritoryCode,
    MT: 'MT' as StateTerritoryCode,
    NE: 'NE' as StateTerritoryCode,
    NV: 'NV' as StateTerritoryCode,
    NH: 'NH' as StateTerritoryCode,
    NJ: 'NJ' as StateTerritoryCode,
    NM: 'NM' as StateTerritoryCode,
    NY: 'NY' as StateTerritoryCode,
    NC: 'NC' as StateTerritoryCode,
    ND: 'ND' as StateTerritoryCode,
    OH: 'OH' as StateTerritoryCode,
    OK: 'OK' as StateTerritoryCode,
    OR: 'OR' as StateTerritoryCode,
    PA: 'PA' as StateTerritoryCode,
    PR: 'PR' as StateTerritoryCode,
    RI: 'RI' as StateTerritoryCode,
    SC: 'SC' as StateTerritoryCode,
    SD: 'SD' as StateTerritoryCode,
    TN: 'TN' as StateTerritoryCode,
    TX: 'TX' as StateTerritoryCode,
    UT: 'UT' as StateTerritoryCode,
    VT: 'VT' as StateTerritoryCode,
    VI: 'VI' as StateTerritoryCode,
    VA: 'VA' as StateTerritoryCode,
    WA: 'WA' as StateTerritoryCode,
    WV: 'WV' as StateTerritoryCode,
    WI: 'WI' as StateTerritoryCode,
    WY: 'WY' as StateTerritoryCode,
    MP: 'MP' as StateTerritoryCode,
    PW: 'PW' as StateTerritoryCode,
    FM: 'FM' as StateTerritoryCode,
    MH: 'MH' as StateTerritoryCode
};