/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JsonLdContext } from './jsonLdContext';

export interface TextProduct { 
    context?: JsonLdContext;
    id?: string;
    wmoCollectiveId?: string;
    issuingOffice?: string;
    issuanceTime?: Date;
    productCode?: string;
    productName?: string;
    productText?: string;
}