/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ZoneForecastPeriods { 
    /**
     * A sequential identifier number.
     */
    number: number;
    /**
     * A textual description of the period.
     */
    name: string;
    /**
     * A detailed textual forecast for the period.
     */
    detailedForecast: string;
}