/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeometryString } from './geometryString';
import { JsonLdContext } from './jsonLdContext';
import { NWSForecastOfficeId } from './nWSForecastOfficeId';
import { NWSZoneID } from './nWSZoneID';
import { NWSZoneType } from './nWSZoneType';
import { StateTerritoryCode } from './stateTerritoryCode';

export interface Zone { 
    context?: JsonLdContext;
    geometry?: GeometryString;
    id?: string;
    type?: Zone.TypeEnum;
    id?: NWSZoneID;
    type?: NWSZoneType;
    name?: string;
    effectiveDate?: Date;
    expirationDate?: Date;
    state?: StateTerritoryCode | string;
    cwa?: Array<NWSForecastOfficeId>;
    forecastOffices?: Array<string>;
    timeZone?: Array<string>;
    observationStations?: Array<string>;
    radarStation?: string;
}
export namespace Zone {
    export type TypeEnum = 'wx:Zone';
    export const TypeEnum = {
        WxZone: 'wx:Zone' as TypeEnum
    };
}