/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JsonLdContext } from './jsonLdContext';
import { Zone } from './zone';

export interface ZoneCollectionJsonLd { 
    context?: JsonLdContext;
    graph?: Array<Zone>;
}