/**
 * weather.gov API
 * weather.gov API
 *
 * OpenAPI spec version: 1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeometryString } from './geometryString';
import { JsonLdContext } from './jsonLdContext';
import { ZoneForecastPeriods } from './zoneForecastPeriods';

/**
 * An object representing a zone area forecast.
 */
export interface ZoneForecast { 
    context?: JsonLdContext;
    geometry?: GeometryString;
    /**
     * An API link to the zone this forecast is for.
     */
    zone?: string;
    /**
     * The time this zone forecast product was published.
     */
    updated?: Date;
    /**
     * An array of forecast periods.
     */
    periods?: Array<ZoneForecastPeriods>;
}